"""
Copyright (c) 2026 MongoDB Inc.

DISCLAIMER: THESE CODE SAMPLES ARE PROVIDED FOR EDUCATIONAL AND ILLUSTRATIVE PURPOSES ONLY,
TO DEMONSTRATE THE FUNCTIONALITY OF SPECIFIC MONGODB FEATURES.
THEY ARE NOT PRODUCTION-READY AND MAY LACK THE SECURITY HARDENING, ERROR HANDLING, AND TESTING REQUIRED FOR A LIVE ENVIRONMENT.
YOU ARE RESPONSIBLE FOR TESTING, VALIDATING, AND SECURING THIS CODE WITHIN YOUR OWN ENVIRONMENT BEFORE IMPLEMENTATION.
THIS MATERIAL IS PROVIDED "AS IS" WITHOUT WARRANTY OR LIABILITY.
"""

import os

from mongo_x_ray.parsers.base_parser import BaseParser as HCBaseParser


class BaseParser(HCBaseParser):
    """
    Base class for GMD analysis items. Inherits from the health check BaseItem and can be extended with GMD-specific functionality if needed.
    """

    TEMPLATE_FOLDER = os.path.join("templates", "gmd", "snippets")
    TEMPLATE_PACKAGE = "mongo_x_ray_gmd"
